#!/bin/bash
if [[ $# -ne 4 ]]; then
	echo >&2 "Usage: init-cmake-project PROJECT_DIR PROJECT_NAME LIBRARY_NAME EXECUTABLE_NAME"
	echo >&2 ""   
	echo >&2 "Initializes an empty CMake C project"
	exit 2
fi

PROJECT_NAME="$2"
LIBRARY_NAME="$3"
EXECUTABLE_NAME="$4"
PROJECT_DIR="$1/$2"

mkdir -p "${PROJECT_DIR}"
touch "${PROJECT_DIR}/.gitignore"
touch "${PROJECT_DIR}/README.md"
touch "${PROJECT_DIR}/LICENSE.md"
touch "${PROJECT_DIR}/CMakeLists.txt"
mkdir -p "${PROJECT_DIR}/cmake"
mkdir -p "${PROJECT_DIR}/include"
mkdir -p "${PROJECT_DIR}/include/${PROJECT_NAME}"
touch "${PROJECT_DIR}/include/${PROJECT_NAME}/${LIBRARY_NAME}.h"
mkdir -p "${PROJECT_DIR}/src"
touch "${PROJECT_DIR}/src/CMakeLists.txt"
touch "${PROJECT_DIR}/src/${LIBRARY_NAME}.c"
mkdir -p "${PROJECT_DIR}/apps"
touch "${PROJECT_DIR}/apps/CMakeLists.txt"
touch "${PROJECT_DIR}/apps/${EXECUTABLE_NAME}.c"
mkdir -p "${PROJECT_DIR}/tests"
touch "${PROJECT_DIR}/tests/CMakeLists.txt"
touch "${PROJECT_DIR}/tests/test_${LIBRARY_NAME}.c"
mkdir -p "${PROJECT_DIR}/docs"
touch "${PROJECT_DIR}/docs/CMakeLists.txt"
mkdir -p "${PROJECT_DIR}/extern"
mkdir -p "${PROJECT_DIR}/scripts"
mkdir -p "${PROJECT_DIR}/build"


# ----- ./CMakeLists.txt
cat << MAIN_CMAKELISTS > "${PROJECT_DIR}/CMakeLists.txt"
cmake_minimum_required(VERSION 3.11)

project(
	${PROJECT_NAME^}
	VERSION 0.1
	DESCRIPTION "Empty project template"
	LANGUAGES C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_FLAGS "-Wall -Wno-error")

enable_testing()

add_subdirectory(src)
add_subdirectory(extern)
add_subdirectory(apps)
add_subdirectory(tests)
MAIN_CMAKELISTS

# ----- ./src/CMakeLists.txt
cat << SRC_CMAKELISTS > "${PROJECT_DIR}/src/CMakeLists.txt"
set(HEADER_LIST "\${${PROJECT_NAME^}_SOURCE_DIR}/include/${PROJECT_NAME}/${LIBRARY_NAME}.h")

add_library(${PROJECT_NAME}_library ${LIBRARY_NAME}.c \${HEADER_LIST})

target_include_directories(${PROJECT_NAME}_library PUBLIC ../include)
SRC_CMAKELISTS

# ----- ./apps/CMakeLists.txt
cat << APPS_CMAKELISTS > "${PROJECT_DIR}/apps/CMakeLists.txt"
add_executable(${EXECUTABLE_NAME} ${EXECUTABLE_NAME}.c)
target_link_libraries(${EXECUTABLE_NAME} PRIVATE ${PROJECT_NAME}_library)
APPS_CMAKELISTS

# ----- ./extern/CMakeLists.txt
cat << EXTERN_CMAKELISTS > "${PROJECT_DIR}/extern/CMakeLists.txt"
add_library(Unity STATIC Unity/src/unity.c)
target_include_directories(Unity PUBLIC Unity/src)
EXTERN_CMAKELISTS

# ----- ./tests/CMakeLists.txt
cat << TESTS_CMAKELISTS > "${PROJECT_DIR}/tests/CMakeLists.txt"
add_executable(test_${LIBRARY_NAME} test_${LIBRARY_NAME}.c)
target_link_libraries(test_${LIBRARY_NAME} ${PROJECT_NAME}_library Unity)
add_test(test_${PROJECT_NAME}_all test_${LIBRARY_NAME})
TESTS_CMAKELISTS

# ------ ./include/project/library.h
cat << LIBRARY_H > "${PROJECT_DIR}/include/${PROJECT_NAME}/${LIBRARY_NAME}.h"
#ifndef ${PROJECT_NAME^^}_H_
#define ${PROJECT_NAME^^}_H_
#define VERSION 0.1

void print_version(void);
int my_library_function(void);
#endif
LIBRARY_H

# ------ ./src/library.c
cat << LIBRARY_C > "${PROJECT_DIR}/src/${LIBRARY_NAME}.c"
#include <${PROJECT_NAME}/${LIBRARY_NAME}.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void print_version(void)
{
	printf("${PROJECT_NAME^} (version %0.2f)\n", VERSION);
}

/*
	Function used for initial unit test of this library.
	See ../tests/test_${LIBRARY_NAME}.c"
*/
int my_library_function(void)
{
	return 1;
}
LIBRARY_C

# ------ ./apps/app.c
cat << APP_C > "${PROJECT_DIR}/apps/${EXECUTABLE_NAME}.c"
#include <${PROJECT_NAME}/${LIBRARY_NAME}.h>

int main(void)
{
	print_version();
	return 0;
}
APP_C

# ------ ./tests/test_library.c
cat << TEST_LIBRARY_C > "${PROJECT_DIR}/tests/test_${LIBRARY_NAME}.c"
#include <${PROJECT_NAME}/${LIBRARY_NAME}.h>
#include <unity.h>

void setUp(void) {}
void tearDown(void) {}

void test_Should_Run_Library_Function()
{
	TEST_ASSERT_TRUE_MESSAGE(1 == my_library_function(), "Wrong initial function result of library ${LIBRARY_NAME}");
}

int main(void)
{
	UNITY_BEGIN();
	RUN_TEST(test_Should_Run_Library_Function);
	return UNITY_END();
}
TEST_LIBRARY_C

# ----- ./build/build_app.sh
cat << BUILD_SH > "${PROJECT_DIR}/build/build_app.sh"
#!/bin/bash
(
cd "\$( dirname "\${BASH_SOURCE[0]}" )"
cmake ..
make
ctest
)
BUILD_SH
chmod +x "${PROJECT_DIR}/build/build_app.sh"

### ----- Script echo output
echo "Created CMake project ${PROJECT_NAME^} in ${PROJECT_DIR}."
echo "Downloading dependencies into ${PROJECT_DIR}/extern."
if ! git clone https://github.com/ThrowTheSwitch/Unity.git "${PROJECT_DIR}/extern/Unity" 2>/dev/null && [ -d "${PROJECT_DIR}/extern/Unity" ] ; then
	echo "  - Unity Test API is already present at ${PROJECT_DIR}/extern/Unity"
else 
	echo "  + Unity Test API"
fi
echo ""
echo "Done."
echo "Run ${PROJECT_DIR}/build/build_app.sh to build and test the project."


